version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: "581483106272"
    AWS_REGION: "eu-north-1"
    REPO_BACKEND: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/pfe-backend"
    REPO_FRONTEND: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/pfe-frontend"
    REPO_NGINX: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/pfe-nginx"

phases:
  pre_build:
    commands:
      - echo "Login to ECR"
      - aws --version
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 581483106272.dkr.ecr.eu-north-1.amazonaws.com
      - #aws ecr get-login-password --region $AWS_REGION \
        #| docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:-latest}
      - echo "Tag des images:$IMAGE_TAG"

  build:
    commands:
      - echo "Build backend"
      - cd backend && mvn clean package -DskipTests
      - echo "Build image backend"
      - docker build -f Dockerfile -t $REPO_BACKEND:latest .
      - docker tag $REPO_BACKEND:latest $REPO_BACKEND:$IMAGE_TAG
      - cd ..

      - echo "Build frontend"
      - cd frontend
      - npm install
      - npm run build --configuration production
      - cd ..

      - echo "Build image frontend"
      - docker build -f frontend/Dockerfile -t $REPO_FRONTEND:latest frontend/
      - docker tag $REPO_FRONTEND:latest $REPO_FRONTEND:$IMAGE_TAG

      - echo "Build image nginx"
      - docker build -f nginx/Dockerfile -t $REPO_NGINX:latest nginx/
      - docker tag $REPO_NGINX:latest $REPO_NGINX:$IMAGE_TAG

  post_build:
    commands:
      - echo "Pushing images to ECR"
      - docker push $REPO_BACKEND:latest
      - docker push $REPO_BACKEND:$IMAGE_TAG
      - docker push $REPO_FRONTEND:latest
      - docker push $REPO_FRONTEND:$IMAGE_TAG
      - docker push $REPO_NGINX:latest
      - docker push $REPO_NGINX:$IMAGE_TAG

      - echo "Generating imagedefinitions.json"
      - printf '[{"name":"pfeapplicationcontainer","imageUri":"%s"},{"name":"frontendcontainer","imageUri":"%s"},{"name":"nginxcontainer","imageUri":"%s"}]' \
        "$REPO_BACKEND:$IMAGE_TAG" "$REPO_FRONTEND:$IMAGE_TAG" "$REPO_NGINX:$IMAGE_TAG" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
