services:
  mysqldb:
    container_name: mysqlcontainerforapp
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pfe
      MYSQL_USER: Emmanuel
      MYSQL_PASSWORD: 123@Emma
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/dumps:/docker-entrypoint-initdb.d
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-padmin"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      - common-network

  pfeapplication:
    container_name: pfeapplicationcontainer
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: pfeapplication:v1
    restart: unless-stopped
    ports:
      - "8081:8086"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/pfe
      SPRING_DATASOURCE_USERNAME: Emmanuel
      SPRING_DATASOURCE_PASSWORD: 123@Emma
      SPRING_PROFILES_ACTIVE: prod  # si vous utilisez un profil prod pour CORS
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      mysqldb:
        condition: service_healthy
    networks:
      - common-network

  nginx:
    container_name: nginxcontainer
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-custom:v1
    restart: unless-stopped
    ports:
      - "8089:80"  # front end servi sur http://localhost:8089
    depends_on:
      - pfeapplication
    networks:
      - common-network

networks:
  common-network:
    driver: bridge

volumes:
  mysql_data:
