jwt:
  issuer: 'Dev Hydra'
  expiration: 86400000

logging:
  level:
    org:
      springframework:
        security=DEBUG:

management:
  endpoints:
    web:
      exposure:
        include=health:
server:
  port: 8086
spring:
  profiles:
    active: prod
  mail:
    username: 'eloubahasra@gmail.com'
    port: 587
    host: 'smtp.gmail.com'
    password: 'lhlnakruohcdbtpz'
    default-encoding: utf-8
    properties:
      mail:
        mime:
          charset:UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
  application:
    name: pfeapplication
  security:
    enabled: true
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        minimum-idle: 5
        maximum-pool-size: 20
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
      url : jdbc:mysql://localhost:3306/pfe
      username: Emmanuel
      password: 123@Emma
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect
          format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  cache:
    caffeine:
      spec: jwtClaims
cors:
  allowed-origins: "http://localhost:8089"

